version: "3.9"

services:
  postgres-primary:
    image: postgres:18.1

  postgres-replica:
    image: postgres:18.1

  redis:
    image: redis:8.4.0

  kafka:
    image: public.ecr.aws/bitnami/kafka:latest

  rabbitmq:
    image: rabbitmq:4.2.1-management

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest

  prometheus:
    image: prom/prometheus:v3.8.0

  grafana:
    image: grafana/grafana:12.1.4

  tempo:
    image: grafana/tempo:latest

  loki:
    image: grafana/loki:3.5.9
